[powerops]
redis_sentinel_hosts = {% for host in groups['redis'] %}{{ 'api' | kolla_address(host) | put_address_in_context('url') }}:{{ redis_sentinel_port }}{% if not loop.last %},{% endif %}{% endfor %}
redis_sentinel_socket_timeout = 5
redis_master_name = kolla
redis_password = {{ redis_master_password }}
redis_db = 4
region_name = RegionOne
interface = internal
verify = true
lock_ttl = 900
drain_timeout = 600
power_timeout = 180
poll_interval = 5
stable_observations = 3
