[DEFAULT]
enabled_hardware_types = redfish,ipmi
enabled_power_interfaces = redfish,ipmitool
enabled_management_interfaces = redfish,ipmitool
enabled_network_interfaces = noop

[conductor]
automated_clean = false
